import { PrismaClient } from "@prisma/client";
const prisma=new PrismaClient();
const conditions=["Migraines","PTSD","Sleep Apnea","Tinnitus","Hearing Loss","Lumbar Strain","GERD","IBS","Knee Pain","Sinusitis","Rhinitis"];
const evidence=["Medical Records","Service Treatment Records","Personnel Records","Buddy Statements","Spouse Statements","Private Medical Opinions","VA Records","Deployment Orders","Photos","Medical Journals"];
const forms=["21-526EZ","20-0995","20-0996","10182","21-4138","21-4142","21-4142a","21-8940","21-4192","DBQs"];
const templates=["Personal Statement","Buddy Statement","Spouse Statement","Supervisor Statement","Toxic Exposure Statement","Secondary Condition Statement","Independent Medical Opinion Request","Employer Statement","Symptom Log Cover Letter","Treatment Summary"];
const slug=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
async function main(){for(const name of conditions)await prisma.condition.upsert({where:{slug:slug(name)},update:{},create:{slug:slug(name),name,overview:`An educational overview of ${name}, including symptoms, treatment history, and service-connection concepts.`,ratingCriteria:"Ratings depend on the severity, frequency, and functional impact documented in current VA criteria.",typicalEvidence:"Current diagnosis, service records, treatment notes, symptom history, and credible supporting statements.",requiredDiagnosis:"A qualified clinician should document the current condition when a diagnosis is medically required.",commonMistakes:"Leaving gaps in the timeline or describing symptoms without explaining their functional impact.",helpfulDocumentation:"Treatment summaries, symptom logs, relevant service records, and statements from people with firsthand knowledge."}});for(const name of evidence)await prisma.evidenceType.upsert({where:{slug:slug(name)},update:{},create:{slug:slug(name),name,category:"Supporting evidence",description:`Records or statements in the ${name} category.`,purpose:"Help establish a current disability, an in-service event, or a connection between them.",strength:"Strength depends on relevance, credibility, specificity, and consistency with the full record.",whenToUse:"When it directly supports a fact your claim needs to establish.",commonMistakes:"Submitting unrelated material without dates, context, or a clear link to the claimed condition.",examples:"Dated records, signed statements, clinician notes, or official orders."}});for(const formNumber of forms)await prisma.vAForm.upsert({where:{slug:slug(formNumber)},update:{},create:{slug:slug(formNumber),formNumber,name:formNumber==="DBQs"?"Disability Benefits Questionnaires":`VA Form ${formNumber}`,purpose:"Supports a specific step in the VA claims or review process.",description:"Review the current official VA instructions before completing this form.",whenToUse:"Use only for the process described in the official form instructions.",completedBy:"Veteran, representative, employer, or clinician as specified by the form.",typicalMistakes:"Using an outdated version, missing signatures, or omitting required sections.",status:"Current version should be verified at VA.gov"}});for(const name of templates)await prisma.template.upsert({where:{slug:slug(name)},update:{},create:{slug:slug(name),name,category:"Statement",purpose:`Organize the facts commonly included in a ${name.toLowerCase()}.`,instructions:"Replace every bracketed prompt with specific, truthful, firsthand information. Remove sections that do not apply.",body:`[Your name]\n[Date]\n\nI am providing this ${name.toLowerCase()} to describe [relevant facts].\n\n[Include dates, locations, observations, and functional impact.]\n\nI certify that this statement is true and correct to the best of my knowledge.`}})}
main().finally(()=>prisma.$disconnect());
