import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { conditions, getCondition } from "@/lib/conditions";
import { ArrowLeft, ArrowRight, BookOpen, CalendarDays, ExternalLink, Info } from "lucide-react";
import "../conditions.css";
export function generateStaticParams(){return conditions.map(c=>({slug:c.slug}))}
export default async function ConditionPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const c=getCondition(slug);if(!c)notFound();return <AppShell current="conditions"><div className="condition-detail"><a href="/conditions" className="back-link"><ArrowLeft size={15}/>All conditions</a><header className="detail-hero"><span className="condition-category">{c.category}</span><h1>{c.name}</h1><p>{c.short}</p><div className="verified"><CalendarDays size={14}/>Educational summary reviewed July 12, 2026</div></header><div className="detail-layout"><main><DetailSection title="Overview"><p>{c.overview}</p></DetailSection><DetailSection title="How the rating schedule approaches this condition"><p>{c.schedule}</p><div className="factor-list">{c.ratingFactors.map(x=><div key={x}><span/> {x}</div>)}</div><div className="source-note"><BookOpen size={17}/><div><strong>Read the controlling source</strong><p>Summaries can omit details and regulations can change.</p><a href={c.sourceUrl} target="_blank" rel="noreferrer">{c.sourceLabel}<ExternalLink size={13}/></a></div></div></DetailSection><DetailSection title="Evidence that may be useful"><BulletList items={c.evidence}/></DetailSection><DetailSection title="Helpful documentation habits"><BulletList items={c.documentation}/></DetailSection><DetailSection title="Common preparation gaps"><BulletList items={c.mistakes}/></DetailSection></main><aside><div className="detail-aside"><span className="kicker">Related topics</span>{c.related.map(x=><div key={x}>{x}</div>)}</div><div className="detail-aside action-aside"><span className="kicker">Ready to organize?</span><h2>Start a preparation draft</h2><p>Answer guided questions and build an evidence checklist.</p><a className="button primary" href="/claim-builder">Build a claim <ArrowRight size={15}/></a></div><div className="detail-warning"><Info size={16}/><p>This guide does not diagnose a condition, establish service connection, or calculate a rating.</p></div></aside></div><footer className="disclaimer">Veteran Claims Companion is an independent educational resource and is not affiliated with the U.S. Department of Veterans Affairs.</footer></div></AppShell>}
function DetailSection({title,children}:{title:string;children:React.ReactNode}){return <section className="detail-section"><h2>{title}</h2>{children}</section>}
function BulletList({items}:{items:string[]}){return <ul className="detail-list">{items.map(x=><li key={x}>{x}</li>)}</ul>}
