import { ArrowLeft, ExternalLink, Info, ShieldCheck } from "lucide-react";
import "../legal.css";

const contact=process.env.PRIVACY_CONTACT_EMAIL;

export default function PrivacyPage(){return <main className="legal-page"><a className="legal-back" href="/"><ArrowLeft size={14}/>Debrief home</a><header><ShieldCheck size={25}/><span className="kicker">Effective July 18, 2026</span><h1>Alpha Privacy Notice</h1><p>This notice explains the data practices implemented in the current closed-alpha build. It is not a certification that Debrief is approved for real health information.</p></header>
  <div className="legal-alert"><Info size={17}/><p><strong>Use fictional information only.</strong> Do not provide real medical records, health information, Social Security numbers, VA file numbers, or another person’s information during alpha testing.</p></div>
  <section><h2>Information Debrief handles</h2><ul><li><strong>Google sign-in data:</strong> name, email address, profile image, and Google account identifier used for authentication.</li><li><strong>Workspace data:</strong> questionnaire answers, statement drafts, timelines, evidence statuses, progress, and condition labels you enter.</li><li><strong>Test documents:</strong> fictional PDF, JPEG, or PNG files you intentionally upload, plus filename, type, size, checksum, storage location, and upload date.</li><li><strong>Security records:</strong> database sessions and limited audit events for workspace creation and test-document upload, download, and deletion. Audit metadata excludes document names and contents.</li></ul></section>
  <section><h2>How the information is used</h2><p>Data is used only to authenticate testers, provide private saved workspaces, generate requested drafts or preparation PDFs, maintain document ownership controls, diagnose errors, and protect the alpha service. Debrief does not sell personal information or use Google sign-in data for advertising or generalized AI training.</p></section>
  <section><h2>Service providers and transfers</h2><p>The application relies on Google for sign-in and on the configured hosting, PostgreSQL database, and private object-storage providers to operate the service. If AI drafting is later enabled, questionnaire answers are sent to OpenAI only after an explicit in-product acknowledgement; the optional display name is excluded and API storage is disabled in the request. The non-AI guided narrative does not send answers to OpenAI.</p></section>
  <section><h2>Cookies and browser storage</h2><p>Debrief uses essential authentication cookies. Signed-out drafts may be stored in the browser’s local storage. The alpha does not include advertising cookies or cross-site analytics.</p></section>
  <section><h2>Retention and deletion</h2><p>Account data remains until the tester deletes individual workspaces or uses <strong>Account and data → Delete account and data</strong>. Account deletion removes database records and stored test documents from active application storage. Hosting and infrastructure providers may retain encrypted backups or security logs under their own configured retention schedules. The alpha administrator must document those vendor schedules before real-data use.</p></section>
  <section><h2>Security and health-data status</h2><p>Debrief uses account-scoped access checks, database sessions, private test-file storage, file-signature checks, random storage keys, request limits, and security headers. The alpha does not have malware scanning, a completed production threat assessment, or a determination that its controls meet requirements for real health data. Debrief does not claim to be HIPAA compliant.</p></section>
  <section><h2>Your choices</h2><p>You can use public educational pages without signing in, remove individual claims and test documents, delete the entire account, or stop participating in the alpha. For a privacy or deletion problem, {contact?<a href={`mailto:${contact}`}>{contact}</a>:<>contact the alpha administrator who invited you</>}.</p></section>
  <section><h2>Google user data</h2><p>Information received through Google sign-in is limited to authentication and account identification. Debrief’s use and transfer of that information follows the Google API Services User Data Policy, including applicable Limited Use requirements.</p></section>
  <section><h2>Important legal scope</h2><p>Depending on the product’s future data sources and relationships, laws beyond HIPAA may apply, including the FTC Act and the FTC Health Breach Notification Rule. This notice must be reviewed by qualified counsel before accepting real claimant information or opening access beyond a controlled fictional-data alpha.</p><div className="legal-sources"><a href="https://www.ftc.gov/business-guidance/privacy-security/health-privacy" target="_blank" rel="noreferrer">FTC health privacy guidance <ExternalLink size={12}/></a><a href="https://www.hhs.gov/hipaa/for-professionals/special-topics/health-apps/index.html" target="_blank" rel="noreferrer">HHS health-app guidance <ExternalLink size={12}/></a></div></section>
  <footer><a href="/terms">Alpha Terms of Use</a><span>Debrief is independent and is not affiliated with VA.</span></footer>
</main>}
