"use client";

import { AlertTriangle, ArrowRight, Download, FilePlus2, FileText, FolderPlus, LoaderCircle, Trash2, UploadCloud } from "lucide-react";
import { useMemo, useRef, useState } from "react";

type Workspace={id:string;title:string;updatedAt:string;_count:{documents:number}};
type DocumentRecord={id:string;claimId:string;originalName:string;mimeType:string;size:number;status:string;provider:string;createdAt:string};

export function DocumentIntake({initialWorkspaces,initialDocuments}:{initialWorkspaces:Workspace[];initialDocuments:DocumentRecord[]}){
  const [workspaces,setWorkspaces]=useState(initialWorkspaces);const [documents,setDocuments]=useState(initialDocuments);
  const [claimId,setClaimId]=useState(initialWorkspaces[0]?.id||"");const [workspaceName,setWorkspaceName]=useState("");
  const [file,setFile]=useState<File|null>(null);const [confirmed,setConfirmed]=useState(false);const [dragging,setDragging]=useState(false);
  const [working,setWorking]=useState<""|"workspace"|"upload">("");const [downloadingId,setDownloadingId]=useState("");const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const inputRef=useRef<HTMLInputElement>(null);const visibleDocuments=useMemo(()=>documents.filter(item=>item.claimId===claimId),[documents,claimId]);
  const selectedWorkspace=workspaces.find(item=>item.id===claimId);

  function chooseFile(next?:File){if(!next)return;if(next.size>4*1024*1024){setFile(null);setError("Test files must be 4 MB or smaller.");setNotice("");return}setFile(next);setError("");setNotice("")}
  async function createWorkspace(event:React.FormEvent){event.preventDefault();setWorking("workspace");setError("");try{const response=await fetch("/api/workspaces",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:workspaceName})});const data=await response.json() as {workspace?:Workspace;error?:string};if(!response.ok||!data.workspace)throw new Error(data.error||"The workspace could not be created.");setWorkspaces(items=>[data.workspace!,...items]);setClaimId(data.workspace.id);setWorkspaceName("");setNotice("Workspace created. Add a fictional document or continue directly to claim setup.")}catch(reason){setError(reason instanceof Error?reason.message:"The workspace could not be created.")}finally{setWorking("")}}
  async function upload(){if(!file||!claimId||!confirmed)return;setWorking("upload");setError("");setNotice("");const form=new FormData();form.set("file",file);form.set("claimId",claimId);form.set("syntheticConfirmed","true");try{const response=await fetch("/api/documents",{method:"POST",body:form});const data=await response.json() as {document?:DocumentRecord;error?:string};if(!response.ok||!data.document)throw new Error(data.error||"The test document could not be uploaded.");setDocuments(items=>[data.document!,...items]);setWorkspaces(items=>items.map(item=>item.id===claimId?{...item,_count:{documents:item._count.documents+1}}:item));setFile(null);setConfirmed(false);if(inputRef.current)inputRef.current.value="";setNotice("Document stored. Continue to claim setup when you are ready.")}catch(reason){setError(reason instanceof Error?reason.message:"The test document could not be uploaded.")}finally{setWorking("")}}
  async function remove(document:DocumentRecord){if(!window.confirm(`Permanently delete ${document.originalName}?`))return;setError("");const response=await fetch(`/api/documents/${encodeURIComponent(document.id)}`,{method:"DELETE"});if(!response.ok){const data=await response.json().catch(()=>({})) as {error?:string};setError(data.error||"The document could not be deleted.");return}setDocuments(items=>items.filter(item=>item.id!==document.id));setWorkspaces(items=>items.map(item=>item.id===document.claimId?{...item,_count:{documents:Math.max(0,item._count.documents-1)}}:item));setNotice("The document was permanently deleted.")}
  async function download(item:DocumentRecord){setDownloadingId(item.id);setError("");try{const response=await fetch(`/api/documents/${encodeURIComponent(item.id)}/download-link`,{method:"POST"});const data=await response.json().catch(()=>({})) as {url?:string;error?:string};if(!response.ok||!data.url?.startsWith("/api/documents/"))throw new Error(data.error||"A secure download link could not be created.");const link=window.document.createElement("a");link.href=data.url;link.setAttribute("aria-hidden","true");window.document.body.appendChild(link);link.click();link.remove()}catch(reason){setError(reason instanceof Error?reason.message:"The document could not be downloaded.")}finally{setDownloadingId("")}}

  return <div className="intake-wrap">
    <header className="intake-hero"><span className="kicker">Claim workspace</span><h1>Organize documents, then start the claim</h1><p>Create one workspace for this condition. Documents are optional—you can continue to the questionnaire whenever you are ready.</p></header>
    <nav className="workspace-flow" aria-label="Claim preparation flow"><span className="active">1. Documents</span><span>2. Build claim</span><span>3. Verify statement</span><span>4. Claim package</span></nav>
    <div className="test-only-warning"><AlertTriangle size={20}/><div><strong>Fictional test files only</strong><p>Do not upload real medical records or personal identifiers. Production health-data controls and malware scanning are not enabled.</p></div></div>

    {!workspaces.length?<section className="workspace-start"><span className="kicker">First step</span><h2>Create a workspace</h2><p>Use the condition or issue as the workspace name. You can change the claim details in the questionnaire.</p><form onSubmit={createWorkspace}><label className="intake-field"><span>Workspace name</span><input autoFocus value={workspaceName} onChange={event=>setWorkspaceName(event.target.value)} placeholder="For example, Tinnitus" maxLength={160}/></label><button className="button primary" disabled={!workspaceName.trim()||Boolean(working)}>{working==="workspace"?<LoaderCircle className="spin" size={16}/>:<FolderPlus size={16}/>}Create workspace</button></form>{error&&<p className="intake-message error" role="alert">{error}</p>}</section>:<>
      <section className="workspace-toolbar"><label className="intake-field"><span>Current workspace</span><select value={claimId} onChange={event=>{setClaimId(event.target.value);setError("");setNotice("")}}>{workspaces.map(item=><option value={item.id} key={item.id}>{item.title} · {item._count.documents} {item._count.documents===1?"file":"files"}</option>)}</select></label><details><summary>Create another workspace</summary><form onSubmit={createWorkspace}><label className="intake-field"><span>Workspace name</span><input value={workspaceName} onChange={event=>setWorkspaceName(event.target.value)} placeholder="Condition or issue" maxLength={160}/></label><button className="button secondary" disabled={!workspaceName.trim()||Boolean(working)}>{working==="workspace"?<LoaderCircle className="spin" size={15}/>:<FolderPlus size={15}/>}Create</button></form></details></section>

      <main className="upload-panel simplified-upload"><div className="upload-heading"><div><span className="kicker">Optional documents</span><h2>{selectedWorkspace?.title}</h2></div><span>PDF, JPEG, or PNG · 4 MB</span></div>
        <div className={`document-drop ${dragging?"dragging":""} ${file?"selected":""}`} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);chooseFile(event.dataTransfer.files[0])}}><input ref={inputRef} type="file" aria-label="Choose a fictional test document" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={event=>chooseFile(event.target.files?.[0])}/>{file?<><FileText size={27}/><strong>{file.name}</strong><small>{formatBytes(file.size)} · ready for validation</small><button type="button" onClick={()=>inputRef.current?.click()}>Choose a different file</button></>:<><UploadCloud size={29}/><strong>Drop a fictional document here</strong><small>or choose a PDF, JPEG, or PNG</small><button type="button" onClick={()=>inputRef.current?.click()}><FilePlus2 size={14}/>Choose test file</button></>}</div>
        {file&&<><label className="synthetic-confirm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/><span><strong>I confirm this is an entirely fictional test document.</strong><small>It contains no real person’s health information, identifiers, or records.</small></span></label><button type="button" className="button primary intake-upload-button" disabled={!confirmed||Boolean(working)} onClick={upload}>{working==="upload"?<LoaderCircle className="spin" size={16}/>:<UploadCloud size={16}/>}Upload document</button></>}
        {error&&<p className="intake-message error" role="alert">{error}</p>}{notice&&<p className="intake-message success" role="status">{notice}</p>}
        <div className="document-list"><div className="document-list-title"><h3>Documents</h3><span>{visibleDocuments.length}</span></div>{visibleDocuments.length?visibleDocuments.map(document=><article key={document.id}><span className="document-icon"><FileText size={18}/></span><div><strong>{document.originalName}</strong><small>{formatBytes(document.size)} · Uploaded {formatDate(document.createdAt)}</small></div><div className="document-actions"><button type="button" disabled={downloadingId===document.id} onClick={()=>void download(document)} aria-label={`Download ${document.originalName}`}>{downloadingId===document.id?<LoaderCircle className="spin" size={15}/>:<Download size={15}/>}</button><button type="button" onClick={()=>void remove(document)} aria-label={`Delete ${document.originalName}`}><Trash2 size={15}/></button></div></article>):<div className="empty-documents"><FileText size={22}/><p>No documents added. You may continue without uploading anything.</p></div>}</div>
      </main>
      <section className="intake-next"><div><span className="kicker">Next step</span><h2>Start building this claim</h2><p>The questionnaire will save into the same workspace. You can return to documents later.</p></div><a className="button primary" href={`/claim-builder?claim=${encodeURIComponent(claimId)}`}>{visibleDocuments.length?"Continue to claim setup":"Skip documents for now"}<ArrowRight size={16}/></a></section>
    </>}
  </div>;
}

function formatBytes(value:number){if(value<1024)return`${value} bytes`;if(value<1024*1024)return`${(value/1024).toFixed(1)} KB`;return`${(value/(1024*1024)).toFixed(1)} MB`}
function formatDate(value:string){return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value))}
