import { ArrowLeft, ExternalLink, FileCheck2, Info } from "lucide-react";
import "../legal.css";
import Link from "next/link";

const contact=process.env.PRIVACY_CONTACT_EMAIL;

export default function TermsPage(){return <main className="legal-page"><Link className="legal-back" href="/"><ArrowLeft size={14}/>Debrief home</Link><header><FileCheck2 size={25}/><span className="kicker">Effective July 18, 2026</span><h1>Alpha Terms of Use</h1><p>These terms define the narrow purpose and limitations of the current invitation-only alpha.</p></header>
  <div className="legal-alert"><Info size={17}/><p><strong>Fictional testing only.</strong> By using this alpha, you agree not to enter real health information, medical records, government identifiers, or another person’s information.</p></div>
  <section><h2>Self-directed educational software</h2><p>Debrief is a self-service organization and education tool. It does not act as your representative, communicate with VA, submit a claim, determine eligibility, provide a medical diagnosis, predict a rating, or provide legal advice. Outputs are drafts and checklists that require independent review.</p></section>
  <section><h2>No government affiliation or endorsement</h2><p>Debrief is not affiliated with, endorsed by, or operated by the U.S. Department of Veterans Affairs or any other government agency. References to VA forms, regulations, and resources are provided for education and should be verified against current official sources.</p></section>
  <section><h2>No accredited representation</h2><p>Using software is not a substitute for representation by a VA-accredited Veterans Service Organization representative, attorney, or claims agent. Debrief does not establish a representative-client relationship and no person associated with the alpha is agreeing to prepare, present, or prosecute an individual claim on a tester’s behalf.</p><div className="legal-sources"><a href="https://www.va.gov/get-help-from-accredited-representative/" target="_blank" rel="noreferrer">Find a VA-accredited representative <ExternalLink size={12}/></a></div></section>
  <section><h2>Your responsibilities</h2><ul><li>Use only fictional scenarios and documents during alpha.</li><li>Keep your Google account and device secure.</li><li>Review generated text for accuracy and remove anything unsupported.</li><li>Do not treat condition summaries as a diagnosis or a statement of likely entitlement.</li><li>Do not rely on Debrief as proof that anything was filed or received.</li><li>Report security or privacy concerns promptly to {contact?<a href={`mailto:${contact}`}>{contact}</a>:<>the alpha administrator who invited you</>}.</li></ul></section>
  <section><h2>Alpha availability</h2><p>The alpha may change, contain errors, lose test data, or be suspended without notice. Features are provided for evaluation as available. Do not rely on the alpha to meet a filing deadline or preserve the only copy of any information.</p></section>
  <section><h2>Feedback</h2><p>You may provide product feedback, but do not include real claimant facts or confidential information. Feedback may be used to improve Debrief.</p></section>
  <section><h2>Privacy and deletion</h2><p>The <Link href="/privacy">Alpha Privacy Notice</Link> describes current data handling. Signed-in testers can delete individual workspaces and documents or delete the entire account through Account and data.</p></section>
  <section><h2>Before any real-data release</h2><p>These alpha terms are not a substitute for product-specific legal advice. Qualified counsel must review veterans-benefit accreditation boundaries, consumer protection, health privacy and breach duties, state privacy requirements, contracts, and these terms before Debrief accepts real claimant information.</p></section>
  <footer><span><Link href="/support">Support</Link> · <Link href="/privacy">Alpha Privacy Notice</Link></span><span>Debrief is independent and is not affiliated with VA.</span></footer>
</main>}
