export type ChangeLogEntry={
  date:string;
  category:"Forms"|"Conditions"|"Claim builder"|"Platform";
  title:string;
  summary:string;
  changes:string[];
  sources?:{label:string;url:string}[];
};

export const changeLog:ChangeLogEntry[]=[
  {date:"2026-07-16",category:"Platform",title:"Added account-based claim saving",summary:"Signed-in users can now save questionnaire workspaces to the hosted database and continue them later from the dashboard or another device.",changes:["Added account-owned claim create, read, update, and delete API routes","Added version checks that prevent an older browser tab from silently overwriting newer work","Added automatic saving after questionnaire changes and visible saving, saved, and error states","Replaced sample dashboard claims with the signed-in user's saved workspaces","Added a browser-only mode for signed-out users and transfer of that draft after sign-in","Added database fields and a migration for versioned questionnaire snapshots","Kept medical-document uploads disabled until private object storage and file-security controls are configured"]},
  {date:"2026-07-13",category:"Claim builder",title:"Introduced fact-to-evidence statement preparation",summary:"Expanded the builder from a general questionnaire into an adaptive preparation workflow that checks facts, chronology, supporting information, and statement accuracy before export.",changes:["Added claim-path-specific questions for original, increased-rating, and secondary claims","Added condition-aware prompts for symptom patterns and functional effects","Added an editable condition timeline with approximate-date labeling","Added a fact-to-evidence map","Added deterministic checks for missing details, vague absolute wording, and unsupported medical conclusions","Added paragraph-by-paragraph accuracy confirmation","Added local workspaces for separate condition statements","Added a downloadable PDF review package with statement, timeline, evidence map, readiness checks, signature area, and page numbering","Kept the PDF clearly separate from an official VA form or proof of submission"],sources:[{label:"VA disability evidence guidance",url:"https://www.va.gov/disability/how-to-file-claim/evidence-needed/"},{label:"VA Form 21-10210",url:"https://www.va.gov/forms/21-10210/"}]},
  {date:"2026-07-13",category:"Claim builder",title:"Added personal-statement drafting",summary:"The guided questionnaire can now produce an editable first-person personal-statement draft using only the information supplied by the veteran.",changes:["Added personal-statement questions for continuity, concrete examples, and optional context","Added server-side AI drafting with input validation, request limits, timeouts, and model-storage disabled","Added explicit acknowledgement before questionnaire answers may be sent to OpenAI","Excluded the optional display name from source material sent to the AI model","Added a clearly labeled guided-template fallback when AI is not configured","Added editing, local draft saving, copying, and plain-text download","Added warnings requiring the veteran to verify every sentence before use"],sources:[{label:"OpenAI Responses API",url:"https://developers.openai.com/api/docs/guides/text"}]},
  {date:"2026-07-13",category:"Conditions",title:"Made rating schemes the center of each condition guide",summary:"Redesigned condition discovery around the question users ask first: which percentage levels exist and what distinguishes them.",changes:["Added a quick rating reference at the top of every condition profile","Added diagnostic-code and shared-formula switching for conditions with multiple rating paths","Separated knee flexion and extension into their correct rating tables","Added verified evaluation levels to condition and diagnostic-code search results","Added A–Z browsing alongside the 14 body-system groups","Clearly labeled indexed codes whose full plain-language tiers still require verification"],sources:[{label:"38 CFR Part 4",url:"https://www.ecfr.gov/current/title-38/chapter-I/part-4"}]},
  {date:"2026-07-13",category:"Forms",title:"Added official form download actions",summary:"Every form resource now provides a direct VA-hosted PDF or the official DBQ download directory alongside its VA information page.",changes:["Added download metadata for all 10 form resources","Recorded the date each destination was verified","Added download actions to form cards and detail pages","Kept DBQs linked to the directory because there is no single universal DBQ PDF"],sources:[{label:"VA forms directory",url:"https://www.va.gov/find-forms/"},{label:"Public DBQ directory",url:"https://www.benefits.va.gov/compensation/dbq_publicdbqs.asp"}]},
  {date:"2026-07-13",category:"Platform",title:"Launched the public change log",summary:"Added a durable place to record content, source, and platform changes as recurring verification work is introduced.",changes:["Added a chronological change history","Added category labels and source links","Added Change log to primary navigation"]},
  {date:"2026-07-13",category:"Conditions",title:"Introduced body-system and diagnostic-code browsing",summary:"Restructured Conditions so plain-language guides sit above a regulatory diagnostic-code catalog rather than implying one condition always has one rating table.",changes:["Added all 14 Part 4 body-system groups","Indexed an initial 27 diagnostic codes","Connected profiles to multiple potentially relevant codes","Added symptom, synonym, body-part, and code search","Prepared source metadata for future eCFR synchronization"],sources:[{label:"38 CFR Part 4",url:"https://www.ecfr.gov/current/title-38/chapter-I/part-4"}]},
  {date:"2026-07-13",category:"Platform",title:"Completed initial MVP reliability fixes",summary:"Corrected misleading prototype behavior before wider review.",changes:["Implemented mobile navigation","Added global condition and form search","Replaced dead links with working destinations or clear availability labels","Made demo dashboard data explicit","Aligned sign-in copy with available authentication"]},
  {date:"2026-07-12",category:"Claim builder",title:"Expanded the guided questionnaire",summary:"Moved beyond a migraine-only flow to support preparation for a broad range of claimed conditions.",changes:["Added condition selection with an Other option","Added claim-path, health, service, treatment, and evidence steps","Added local draft saving and preparation summary"]},
  {date:"2026-07-12",category:"Forms",title:"Created the VA forms library",summary:"Added plain-language guides for frequently used disability and decision-review forms.",changes:["Added searchable form cards","Added form-purpose and completion guidance","Added common-error notes and official VA source pages"]}
];
