export type ChangeLogEntry={
  date:string;
  category:"Forms"|"Conditions"|"Claim builder"|"Platform";
  title:string;
  summary:string;
  changes:string[];
  sources?:{label:string;url:string}[];
};

export const changeLog:ChangeLogEntry[]=[
  {date:"2026-07-19",category:"Platform",title:"Hardened closed-Alpha Google sign-in",summary:"Replaced opaque authentication failures with safe recovery guidance and added controls to detect configuration drift without recording private account data.",changes:["Added a Debrief-branded authentication error page with sanitized reference codes and a fresh-login action","Disabled repeat login submissions while Google authorization is starting","Redirected Production aliases to the canonical Alpha domain before OAuth begins","Added structured authentication events containing timestamps and error codes but no names, emails, tokens, cookies, or claim data","Added a Production environment check for required Google variables, secret strength, HTTPS, and canonical origin","Added repeatable HTTP authentication boundary tests and a dedicated fictional-account callback runbook","Added monthly Auth.js release monitoring and recorded the decision to retain v5 beta during closed Alpha pending defined re-evaluation triggers"]},
  {date:"2026-07-18",category:"Platform",title:"Completed the closed-alpha security and transparency scrub",summary:"Tightened the fictional-data alpha boundary, removed known dependency vulnerabilities, and gave testers clearer control over their account data.",changes:["Removed the unused email-authentication dependency and resolved the npm audit findings","Added browser security headers, no-index directives, cross-origin mutation checks, request-size limits, and alpha storage quotas","Rejected oversized document uploads before reading them into server memory and added client-side size feedback","Added Alpha Privacy Notice and Alpha Terms of Use pages with Google sign-in, AI transfer, retention, health-data, and VA accreditation disclosures","Added account-wide deletion for claims, drafts, sessions, authentication records, and stored test documents","Replaced the inactive settings placeholder with Account and data controls","Added direct VA-accredited-representative guidance and tightened fictional-data warnings across login, intake, and claim building","Rechecked every official VA form destination and replaced the obsolete VA Form 10182 PDF link","Documented unresolved legal, security, accessibility, vendor-retention, and real-data launch gates"]},
  {date:"2026-07-18",category:"Claim builder",title:"Connected intake, questionnaires, and claim-package review",summary:"Simplified the end-to-end preparation path so every screen identifies the next useful action and each condition statement collects in one package view.",changes:["Simplified workspace creation and document upload into one focused intake flow","Added clear continue-to-claim and skip-documents actions","Made every previously visited questionnaire section directly clickable","Separated drafting blockers, wording cautions, optional improvements, and pending evidence on the readiness review","Replaced the export dead end with a condition verification and Add to claim package action","Added an account-level claim package with one statement per condition, preparation status, uploaded-document counts, pending-record reminders, common form resources, and official VA filing guidance"]},
  {date:"2026-07-18",category:"Claim builder",title:"Separated evidence availability from evidence planning",summary:"Each major claim fact can now distinguish available records, personal recollection, witness evidence, pending records, and facts with no identified support.",changes:["Added five explicit evidence statuses to the fact-to-evidence map","Required an evidence type when a fact is marked as supported by an available or pending record","Counted personal recollection and witness evidence as identified support without presenting them as medical records","Stopped records identified but not obtained from counting as available support","Added separate readiness counts for support identified, available records, and records pending","Added pending-record readiness guidance","Converted older string-based saved evidence maps when they are opened","Added evidence statuses and record types to the PDF review package","Added regression coverage for pending records and legacy-map conversion"]},
  {date:"2026-07-18",category:"Claim builder",title:"Expanded fictional claim testing to 40 scenarios",summary:"Added adversarial and edge-case veteran scenarios to exercise the free claim workflow without using real veteran data or paid model calls.",changes:["Expanded the repeatable suite from 18 to 40 fictional scenarios","Added conflicting dates, conflicting frequencies, uncertain memories, treatment gaps, intermittent symptoms, bilateral conditions, attributed clinician opinions, sensitive narratives, witness observations, and uncertain claim paths","Added forbidden-wording, repetition, paragraph-assembly, and cross-claim-isolation checks","Paused drafting when explicit onset years or materially different current frequencies conflict","Made Not sure yet statements neutral instead of treating uncertainty as a claim type","Preserved appropriate uncertainty and clearly attributed medical discussions","Kept zero known questionnaire-style transitions and zero unsupported medical conclusions in generated drafts"]},
  {date:"2026-07-18",category:"Claim builder",title:"Separated new claims from resumable drafts",summary:"Links labeled New claim or Create another claim now always open a clean questionnaire instead of restoring the browser's active unfinished draft.",changes:["Added an explicit fresh-start route for new-claim entry points","Kept selected saved-claim links tied to their claim IDs","Preserved a recoverable browser draft in the local workspace archive before clearing it","Updated dashboard, statement, condition-guide, and post-completion new-claim actions","Kept the general Build a claim navigation route available for resuming an active browser draft"]},
  {date:"2026-07-18",category:"Claim builder",title:"Layered the interview and grounded statement drafting",summary:"Reduced questionnaire overload with progressive disclosure and changed statement drafting to request missing facts before producing a narrative.",changes:["Kept essential questions visible while moving deeper symptom, service, treatment, and evidence questions into optional layers","Removed repeated service-event and specific-example questions","Added claim-path-aware minimum-fact checks before statement generation","Added structured AI responses that either return a cohesive draft or up to three targeted follow-up questions","Prevented drafting when core facts are missing instead of allowing the model to fill gaps","Clearly separated true AI drafting from the non-AI guided-template fallback","Removed AI data-transfer consent from template mode and retained it whenever OpenAI is connected"]},
  {date:"2026-07-18",category:"Platform",title:"Introduced the Debrief briefing experience",summary:"Added a public introduction before the claim workspace and established Debrief as the product identity for MVP review.",changes:["Moved the existing workspace from the public root to /dashboard","Added a responsive mission-brief splash page with sign-in and dashboard entry points","Redesigned sign-in to match the new identity","Updated dashboard and questionnaire links for the new route","Introduced a midnight, graphite, intelligence green, and amber visual system","Recolored the main dashboard as a graphite command center with cool dossier surfaces","Updated product labels and independent-resource disclaimers across the application"]},
  {date:"2026-07-18",category:"Platform",title:"Introduced test document intake",summary:"Added the secure, test-only document foundation for a future evidence-assisted claim workspace without enabling real medical-record processing.",changes:["Added claim-workspace document, page, and audit-event records","Added authenticated fictional PDF, JPEG, and PNG test uploads with a 4 MB limit","Validated file signatures instead of trusting file extensions","Added private storage adapters for local development and Vercel Private Blob","Added owner-restricted list, download, and permanent-delete routes","Added no-store download headers and avoided filenames or contents in audit metadata","Added an explicit fictional-data confirmation and repeated real-record warnings","Kept OCR, AI analysis, malware scanning, and real-record authorization disabled"]},
  {date:"2026-07-16",category:"Platform",title:"Added account-based claim saving",summary:"Signed-in users can now save questionnaire workspaces to the hosted database and continue them later from the dashboard or another device.",changes:["Added account-owned claim create, read, update, and delete API routes","Added version checks that prevent an older browser tab from silently overwriting newer work","Added automatic saving after questionnaire changes and visible saving, saved, and error states","Replaced sample dashboard claims with the signed-in user's saved workspaces","Added a browser-only mode for signed-out users and transfer of that draft after sign-in","Added database fields and a migration for versioned questionnaire snapshots","Kept medical-document uploads disabled until private object storage and file-security controls are configured"]},
  {date:"2026-07-13",category:"Claim builder",title:"Introduced fact-to-evidence statement preparation",summary:"Expanded the builder from a general questionnaire into an adaptive preparation workflow that checks facts, chronology, supporting information, and statement accuracy before export.",changes:["Added claim-path-specific questions for original, increased-rating, and secondary claims","Added condition-aware prompts for symptom patterns and functional effects","Added an editable condition timeline with approximate-date labeling","Added a fact-to-evidence map","Added deterministic checks for missing details, vague absolute wording, and unsupported medical conclusions","Added paragraph-by-paragraph accuracy confirmation","Added local workspaces for separate condition statements","Added a downloadable PDF review package with statement, timeline, evidence map, readiness checks, signature area, and page numbering","Kept the PDF clearly separate from an official VA form or proof of submission"],sources:[{label:"VA disability evidence guidance",url:"https://www.va.gov/disability/how-to-file-claim/evidence-needed/"},{label:"VA Form 21-10210",url:"https://www.va.gov/forms/21-10210/"}]},
  {date:"2026-07-13",category:"Claim builder",title:"Added personal-statement drafting",summary:"The guided questionnaire can now produce an editable first-person personal-statement draft using only the information supplied by the veteran.",changes:["Added personal-statement questions for continuity, concrete examples, and optional context","Added server-side AI drafting with input validation, request limits, timeouts, and model-storage disabled","Added explicit acknowledgement before questionnaire answers may be sent to OpenAI","Excluded the optional display name from source material sent to the AI model","Added a clearly labeled guided-template fallback when AI is not configured","Added editing, local draft saving, copying, and plain-text download","Added warnings requiring the veteran to verify every sentence before use"],sources:[{label:"OpenAI Responses API",url:"https://developers.openai.com/api/docs/guides/text"}]},
  {date:"2026-07-13",category:"Conditions",title:"Made rating schemes the center of each condition guide",summary:"Redesigned condition discovery around the question users ask first: which percentage levels exist and what distinguishes them.",changes:["Added a quick rating reference at the top of every condition profile","Added diagnostic-code and shared-formula switching for conditions with multiple rating paths","Separated knee flexion and extension into their correct rating tables","Added verified evaluation levels to condition and diagnostic-code search results","Added A–Z browsing alongside the 14 body-system groups","Clearly labeled indexed codes whose full plain-language tiers still require verification"],sources:[{label:"38 CFR Part 4",url:"https://www.ecfr.gov/current/title-38/chapter-I/part-4"}]},
  {date:"2026-07-13",category:"Forms",title:"Added official form download actions",summary:"Every form resource now provides a direct VA-hosted PDF or the official DBQ download directory alongside its VA information page.",changes:["Added download metadata for all 10 form resources","Recorded the date each destination was verified","Added download actions to form cards and detail pages","Kept DBQs linked to the directory because there is no single universal DBQ PDF"],sources:[{label:"VA forms directory",url:"https://www.va.gov/find-forms/"},{label:"Public DBQ directory",url:"https://www.benefits.va.gov/compensation/dbq_publicdbqs.asp"}]},
  {date:"2026-07-13",category:"Platform",title:"Launched the public change log",summary:"Added a durable place to record content, source, and platform changes as recurring verification work is introduced.",changes:["Added a chronological change history","Added category labels and source links","Added Change log to primary navigation"]},
  {date:"2026-07-13",category:"Conditions",title:"Introduced body-system and diagnostic-code browsing",summary:"Restructured Conditions so plain-language guides sit above a regulatory diagnostic-code catalog rather than implying one condition always has one rating table.",changes:["Added all 14 Part 4 body-system groups","Indexed an initial 27 diagnostic codes","Connected profiles to multiple potentially relevant codes","Added symptom, synonym, body-part, and code search","Prepared source metadata for future eCFR synchronization"],sources:[{label:"38 CFR Part 4",url:"https://www.ecfr.gov/current/title-38/chapter-I/part-4"}]},
  {date:"2026-07-13",category:"Platform",title:"Completed initial MVP reliability fixes",summary:"Corrected misleading prototype behavior before wider review.",changes:["Implemented mobile navigation","Added global condition and form search","Replaced dead links with working destinations or clear availability labels","Made demo dashboard data explicit","Aligned sign-in copy with available authentication"]},
  {date:"2026-07-12",category:"Claim builder",title:"Expanded the guided questionnaire",summary:"Moved beyond a migraine-only flow to support preparation for a broad range of claimed conditions.",changes:["Added condition selection with an Other option","Added claim-path, health, service, treatment, and evidence steps","Added local draft saving and preparation summary"]},
  {date:"2026-07-12",category:"Forms",title:"Created the VA forms library",summary:"Added plain-language guides for frequently used disability and decision-review forms.",changes:["Added searchable form cards","Added form-purpose and completion guidance","Added common-error notes and official VA source pages"]}
];
