export type VAFormEntry={slug:string;number:string;name:string;category:string;purpose:string;whenToUse:string;completedBy:string;details:string[];mistakes:string[];related:string[];officialUrl:string;status:string;revision?:string};
const f=(x:VAFormEntry)=>x;
export const vaForms:VAFormEntry[]=[
f({slug:"21-526ez",number:"21-526EZ",name:"Application for Disability Compensation and Related Compensation Benefits",category:"Initial or increased claim",purpose:"Apply for VA disability compensation or related compensation benefits.",whenToUse:"Use for a new disability claim or, in many situations, a claim for an increased evaluation. VA also offers an online disability application.",completedBy:"Veteran, service member, or authorized claimant",details:["Identifies each claimed condition","Collects service and treatment information","Includes required notices about evidence","May be accompanied by issue-specific forms"],mistakes:["Using an old downloaded copy","Leaving claimed conditions too vague to identify","Omitting signatures or required identification","Using this form when a decision-review form is the appropriate path"],related:["21-0781 for certain mental-health claims","21-4142 and 21-4142a for private records","DBQs and supporting statements"],officialUrl:"https://www.va.gov/forms/21-526ez/",status:"Current official form",revision:"Check VA.gov for current revision"}),
f({slug:"20-0995",number:"20-0995",name:"Decision Review Request: Supplemental Claim",category:"Decision review",purpose:"Request review of a previously decided issue using new and relevant evidence.",whenToUse:"Use when you disagree with a decision and want VA to consider new and relevant evidence, or for another qualifying supplemental-claim situation.",completedBy:"Claimant or authorized representative",details:["Identifies the specific decided issues","Allows identification of new and relevant evidence","Can authorize VA to obtain certain records","Is one of the Appeals Modernization Act review options"],mistakes:["Failing to identify each issue and decision date","Submitting argument without new and relevant evidence","Mixing different benefit types contrary to the form instructions","Sending evidence without preserving a copy"],related:["20-0996 Higher-Level Review","10182 Board Appeal","21-4142 and 21-4142a"],officialUrl:"https://www.va.gov/forms/20-0995/",status:"Current official form",revision:"Verify on official page"}),
f({slug:"20-0996",number:"20-0996",name:"Decision Review Request: Higher-Level Review",category:"Decision review",purpose:"Ask a more senior reviewer to review an existing decision based on the evidence already in the record.",whenToUse:"Use when you believe VA made an error and you do not need to submit new evidence. An optional informal conference may be requested.",completedBy:"Claimant or authorized representative",details:["Identifies specific issues for review","Uses the record as it existed at the prior decision","Can request an informal conference","Is different from a Supplemental Claim"],mistakes:["Trying to submit new evidence with this review lane","Failing to identify the decision and issues","Providing an unreliable conference contact number","Choosing the lane before understanding its evidence limits"],related:["20-0995 Supplemental Claim","10182 Board Appeal","Decision letter"],officialUrl:"https://www.va.gov/forms/20-0996/",status:"Current official form",revision:"Verify on official page"}),
f({slug:"10182",number:"10182",name:"Decision Review Request: Board Appeal (Notice of Disagreement)",category:"Decision review",purpose:"Appeal one or more VA decisions to the Board of Veterans’ Appeals.",whenToUse:"Use to select a Board review option after a qualifying decision. The available dockets differ in whether evidence or a hearing is allowed.",completedBy:"Appellant or authorized representative",details:["Identifies appealed issues and decision dates","Requires selection of a Board review option","Direct Review, Evidence Submission, and Hearing paths have different rules","Starts an appeal to the Board rather than another review within the agency office"],mistakes:["Using a superseded version","Selecting a docket without understanding evidence limits and timing","Failing to list each appealed issue","Missing the applicable filing deadline"],related:["20-0995 Supplemental Claim","20-0996 Higher-Level Review","Board of Veterans’ Appeals"],officialUrl:"https://www.va.gov/forms/10182/",status:"Revised form available",revision:"Revised May 31, 2026"}),
f({slug:"21-4138",number:"21-4138",name:"Statement in Support of Claim",category:"Supporting statement",purpose:"Provide additional information in support of a VA claim or related matter.",whenToUse:"Use when VA instructions call for this form or when a general signed statement is appropriate. For lay or witness testimony, VA Form 21-10210 may be more specific.",completedBy:"Veteran, claimant, or other person providing the statement",details:["Provides a structured signed statement","Can clarify dates, events, symptoms, or evidence","Should identify the claim or issue clearly","Should remain factual and specific"],mistakes:["Using conclusions instead of firsthand facts","Omitting dates, locations, or context","Including unrelated sensitive details","Forgetting the signature and date"],related:["21-10210 Lay/Witness Statement","Personal statement templates","Claim-specific supporting evidence"],officialUrl:"https://www.va.gov/forms/21-4138/",status:"Current official form",revision:"Verify on official page"}),
f({slug:"21-4142",number:"21-4142",name:"Authorization to Disclose Information to the Department of Veterans Affairs",category:"Private records",purpose:"Authorize a non-VA source to disclose personal or medical information to VA.",whenToUse:"Use when asking VA to obtain records from a private doctor, hospital, employer, insurer, or other non-VA source. VA guidance generally pairs this authorization with Form 21-4142a.",completedBy:"Veteran or person legally authorized to consent",details:["Provides legal authorization for disclosure","May cover sensitive treatment information","Has time-limited authorization language","Works with provider details on 21-4142a"],mistakes:["Submitting 21-4142 without the provider-information form when both are needed","Missing signature or date","Providing an incomplete authorization","Using a version that has expired or been superseded"],related:["21-4142a Provider Information","Private medical records","20-0995 Supplemental Claim"],officialUrl:"https://www.va.gov/forms/21-4142/",status:"Current official form",revision:"August 2024"}),
f({slug:"21-4142a",number:"21-4142a",name:"General Release for Medical Provider Information to the Department of Veterans Affairs",category:"Private records",purpose:"Identify non-VA medical providers and the records VA should request.",whenToUse:"Use with Form 21-4142 when asking VA to obtain private treatment records. List provider addresses, treatment dates, and conditions as completely as possible.",completedBy:"Veteran, claimant, or authorized person",details:["Identifies each provider or facility","Lists approximate treatment dates","Links providers to treated conditions","Helps VA direct its records requests"],mistakes:["Omitting provider addresses","Using overly broad or missing treatment date ranges","Leaving conditions unidentified","Submitting it without the related authorization when required"],related:["21-4142 Authorization","Private treatment records","Provider contact worksheet"],officialUrl:"https://www.va.gov/forms/21-4142a/",status:"Current official form",revision:"Verify on official page"}),
f({slug:"21-8940",number:"21-8940",name:"Veteran’s Application for Increased Compensation Based on Unemployability",category:"Individual Unemployability",purpose:"Apply for Individual Unemployability when service-connected disability prevents substantially gainful employment.",whenToUse:"Use when seeking increased compensation based on unemployability. VA’s online disability application may collect the same information without requiring the PDF.",completedBy:"Veteran",details:["Lists service-connected disabilities affecting employment","Collects employment and earnings history","Collects education and training information","Works with employer information on 21-4192"],mistakes:["Leaving gaps in employment history unexplained","Confusing all health conditions with service-connected conditions relevant to the request","Providing inconsistent dates or earnings","Omitting signature or required employer details"],related:["21-4192 Employer Information","Medical and employment evidence","Individual Unemployability guidance"],officialUrl:"https://www.va.gov/forms/21-8940/",status:"Current official form",revision:"Verify on official page"}),
f({slug:"21-4192",number:"21-4192",name:"Request for Employment Information in Connection with Claim for Disability Benefits",category:"Individual Unemployability",purpose:"Provide employer information for a Veteran seeking Individual Unemployability benefits.",whenToUse:"The Veteran’s most recent employer completes and submits this form in connection with an Individual Unemployability claim.",completedBy:"Employer—not the Veteran",details:["Confirms employment dates and earnings","Describes concessions or time lost","States the reason employment ended","Supports the related 21-8940 application"],mistakes:["Veteran completing the employer certification","Employer omitting signature or contact details","Dates or earnings conflicting with 21-8940 without explanation","Waiting without documenting attempts to obtain the form"],related:["21-8940 Unemployability Application","Employment records","Individual Unemployability guidance"],officialUrl:"https://www.va.gov/forms/21-4192/",status:"Current official form",revision:"August 2024"}),
f({slug:"dbqs",number:"DBQs",name:"Public Disability Benefits Questionnaires",category:"Medical evidence",purpose:"Collect condition-specific medical findings that may support VA’s evaluation of a disability claim.",whenToUse:"A private health care provider may complete an appropriate public DBQ. VA may still require an additional claim examination, and some DBQs are not available for public use.",completedBy:"Qualified health care provider; requirements vary by questionnaire",details:["Choose the questionnaire matching the condition","Complete every applicable clinician-information block","Provider must sign and date the form","VA may verify authenticity and request another examination"],mistakes:["Veteran completing clinical findings intended for a provider","Using an old DBQ saved from another website","Paying a provider without understanding VA does not reimburse the cost","Assuming a private DBQ guarantees VA will not schedule an examination"],related:["Condition Library","Private medical evidence","VA claim examination"],officialUrl:"https://www.benefits.va.gov/compensation/dbq_publicdbqs.asp",status:"Official public DBQ directory",revision:"Forms vary—download fresh copies"})
];
export const formCategories=["All",...Array.from(new Set(vaForms.map(x=>x.category)))];
export function getVAForm(slug:string){return vaForms.find(x=>x.slug===slug)}

export type VAFormDownload={url:string;label:string;kind:"pdf"|"directory";verified:string};
export const VA_FORM_DOWNLOADS_VERIFIED="July 13, 2026";
export const vaFormDownloads:Record<string,VAFormDownload>={
  "21-526ez":{url:"https://www.vba.va.gov/pubs/forms/VBA-21-526EZ-ARE.pdf",label:"Download PDF",kind:"pdf",verified:VA_FORM_DOWNLOADS_VERIFIED},
  "20-0995":{url:"https://www.vba.va.gov/pubs/forms/VBA-20-0995-ARE.pdf",label:"Download PDF",kind:"pdf",verified:VA_FORM_DOWNLOADS_VERIFIED},
  "20-0996":{url:"https://www.vba.va.gov/pubs/forms/VBA-20-0996-ARE.pdf",label:"Download PDF",kind:"pdf",verified:VA_FORM_DOWNLOADS_VERIFIED},
  "10182":{url:"https://www.vba.va.gov/pubs/forms/VBA-10182-ARE.pdf",label:"Download PDF",kind:"pdf",verified:VA_FORM_DOWNLOADS_VERIFIED},
  "21-4138":{url:"https://www.vba.va.gov/pubs/forms/VBA-21-4138-ARE.pdf",label:"Download PDF",kind:"pdf",verified:VA_FORM_DOWNLOADS_VERIFIED},
  "21-4142":{url:"https://www.vba.va.gov/pubs/forms/VBA-21-4142-ARE.pdf",label:"Download PDF",kind:"pdf",verified:VA_FORM_DOWNLOADS_VERIFIED},
  "21-4142a":{url:"https://www.vba.va.gov/pubs/forms/VBA-21-4142a-ARE.pdf",label:"Download PDF",kind:"pdf",verified:VA_FORM_DOWNLOADS_VERIFIED},
  "21-8940":{url:"https://www.vba.va.gov/pubs/forms/VBA-21-8940-ARE.pdf",label:"Download PDF",kind:"pdf",verified:VA_FORM_DOWNLOADS_VERIFIED},
  "21-4192":{url:"https://www.vba.va.gov/pubs/forms/VBA-21-4192-ARE.pdf",label:"Download PDF",kind:"pdf",verified:VA_FORM_DOWNLOADS_VERIFIED},
  "dbqs":{url:"https://www.benefits.va.gov/compensation/dbq_publicdbqs.asp",label:"Browse DBQ downloads",kind:"directory",verified:VA_FORM_DOWNLOADS_VERIFIED}
};
export function getVAFormDownload(slug:string){return vaFormDownloads[slug]}
