import {notFound} from "next/navigation";
import {AppShell} from "@/components/app-shell";
import {getVAForm,vaForms} from "@/lib/va-forms";
import {ArrowLeft,CheckCircle2,ExternalLink,FileCheck2,Info,UserRound} from "lucide-react";
import "../forms.css";
export function generateStaticParams(){return vaForms.map(f=>({slug:f.slug}))}
export default async function FormPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const f=getVAForm(slug);if(!f)notFound();return <AppShell current="forms"><div className="form-detail"><a href="/forms" className="forms-back"><ArrowLeft size={15}/>All forms</a><header className="form-detail-hero"><div><span className="form-number large">{f.number}</span><span className="form-category">{f.category}</span></div><h1>{f.name}</h1><p>{f.purpose}</p><div className="form-current"><CheckCircle2 size={14}/>{f.status} · {f.revision}</div></header><div className="form-detail-layout"><main><FormSection title="When this form is commonly used"><p>{f.whenToUse}</p></FormSection><FormSection title="Who completes it"><div className="who-completes"><UserRound size={18}/><strong>{f.completedBy}</strong></div></FormSection><FormSection title="What it helps document"><FormList items={f.details}/></FormSection><FormSection title="Common mistakes to avoid"><FormList items={f.mistakes}/></FormSection><div className="official-form-box"><FileCheck2 size={22}/><div><span className="kicker">Official source</span><h2>Open the current VA page</h2><p>Review the official instructions and download or complete the current version there.</p><a href={f.officialUrl} target="_blank" rel="noreferrer" className="button primary">Open on VA.gov <ExternalLink size={14}/></a></div></div></main><aside><div className="form-side"><span className="kicker">Related resources</span>{f.related.map(x=><div key={x}>{x}</div>)}</div><div className="form-side form-warning"><Info size={16}/><p>Do not send completed forms or personal information to Veteran Claims Companion. This application does not submit claims.</p></div></aside></div><footer className="disclaimer">Veteran Claims Companion is an independent educational resource and is not affiliated with the U.S. Department of Veterans Affairs.</footer></div></AppShell>}
function FormSection({title,children}:{title:string;children:React.ReactNode}){return <section className="form-section"><h2>{title}</h2>{children}</section>}
function FormList({items}:{items:string[]}){return <ul>{items.map(x=><li key={x}>{x}</li>)}</ul>}
